test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

	args.peertube_url = "https://domain.tld"
	args.runner_token = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
