#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# CHANGE REMOTE RUNNER URL INSIDE PEERTUBE
#=================================================
ynh_script_progression "Removing the runner from Peertube, registering it with the new URL and name..."

pushd "$install_dir"
  ynh_exec_as_app NODE_CONFIG_DIR="$install_dir/config" NODE_ENV=production node "$install_dir/node_modules/@peertube/peertube-runner" unregister --url $peertube_url --registration-token $runner_token --runner-name $app\_$(hostname)
  ynh_exec_as_app NODE_CONFIG_DIR="$install_dir/config" NODE_ENV=production node "$install_dir/node_modules/@peertube/peertube-runner" register --url $peertube_url --registration-token $runner_token --runner-name $app\_$(hostname)
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
