#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Installing PeerTube remote runner npm module..."

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
pushd "$install_dir"

  ynh_hide_warnings ynh_exec_as_app node_load_PATH NODE_CONFIG_DIR="$install_dir/config" NODE_ENV=production npm install @peertube/peertube-runner
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding PeerTube runner service $app..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="PeerTube remote runner" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# SPECIFIC FINALIZATION
#=================================================
# RUNNER REGISTRATION
#=================================================
ynh_script_progression "Registering the runner on Peertube server..."

runner_id=$(ynh_string_random --length=5 --filter='0-9')
ynh_app_setting_set --key='runner_id' --value=$runner_id

pushd "$install_dir"

  ynh_hide_warnings ynh_exec_as_app node_load_PATH NODE_CONFIG_DIR="$install_dir/config" NODE_ENV=production node "$install_dir/node_modules/@peertube/peertube-runner" register --url $peertube_url --registration-token $runner_token --runner-name $app\_$runner_id
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
